# Generated by Django 6.0.7 on 2026-08-12 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0003_rename_consultatio_assigne_idx_consultatio_assigne_76855d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_reference', models.CharField(db_index=True, editable=False, help_text='Auto-generated reference, e.g. CASE-2026-0001.', max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('case_type', models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('FAMILY', 'Family'), ('PROPERTY', 'Property'), ('CORPORATE', 'Corporate'), ('CONSUMER', 'Consumer'), ('TAX', 'Tax'), ('OTHER', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='OPEN', max_length=20)),
                ('start_date', models.DateField()),
                ('court', models.CharField(blank=True, default='', max_length=255)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=255)),
                ('bench', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('cnr_number', models.CharField(blank=True, default='', max_length=50)),
                ('filing_number', models.CharField(blank=True, default='', max_length=50)),
                ('registration_number', models.CharField(blank=True, default='', max_length=50)),
                ('official_court_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to=settings.AUTH_USER_MODEL)),
                ('originating_consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='consultations.consultation')),
                ('practice_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='consultations.practicearea')),
                ('responsible_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_cases', to=settings.AUTH_USER_MODEL)),
                ('supporting_paralegal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='cases_case_client__933763_idx'), models.Index(fields=['responsible_lawyer', '-created_at'], name='cases_case_respons_e450f7_idx'), models.Index(fields=['status', '-created_at'], name='cases_case_status_f8be30_idx')],
            },
        ),
    ]
