# Generated by Django 6.0.7 on 2026-08-13 01:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assistant_lawyers',
            field=models.ManyToManyField(blank=True, related_name='assistant_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
