# Generated by Django 6.0.7 on 2026-08-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_assistant_lawyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='matter_category',
            field=models.CharField(choices=[('ADVISORY', 'Advisory'), ('DOCUMENTATION', 'Documentation'), ('COMPLIANCE', 'Compliance'), ('LEGAL_NOTICE', 'Legal Notice'), ('MEDIATION', 'Mediation'), ('POLICE_MATTER', 'Police Matter'), ('COURT_LITIGATION', 'Court Litigation'), ('APPEAL', 'Appeal'), ('ARBITRATION', 'Arbitration'), ('EXECUTION', 'Execution'), ('RETAINER', 'Retainer')], db_index=True, default='COURT_LITIGATION', max_length=50),
        ),
        migrations.AddField(
            model_name='case',
            name='matter_stage',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('UNDER_REVIEW', 'Under Review'), ('PRE_LITIGATION', 'Pre-Litigation'), ('NOTICE_ISSUED', 'Notice Issued'), ('FIR_REGISTERED', 'FIR Registered'), ('INVESTIGATION', 'Investigation'), ('COURT_PROCEEDINGS', 'Court Proceedings'), ('APPEAL_PROCEEDINGS', 'Appeal Proceedings'), ('SETTLEMENT', 'Settlement'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='UNDER_REVIEW', max_length=50),
        ),
    ]
