# Generated by Django 6.0.7 on 2026-09-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_courtproceeding_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='appointment_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lawyer-configured fee in INR for appointments on this case.', max_digits=10, null=True),
        ),
    ]
