# Generated by Django 6.0.7 on 2026-10-08 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_appointment_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated reference, e.g. HRNG-2026-0001.', max_length=64, unique=True)),
                ('hearing_date', models.DateField(db_index=True)),
                ('court', models.CharField(blank=True, default='', max_length=255)),
                ('hearing_type', models.CharField(blank=True, default='Regular Hearing', help_text='Hearing stage or type (e.g. Preliminary Hearing, Arguments, Evidence).', max_length=100)),
                ('proceedings', models.TextField(blank=True, default='', help_text='Record of what happened/transpired during the court hearing.')),
                ('outcome', models.CharField(blank=True, default='', help_text='Outcome or status from this hearing (e.g. Adjourned, Orders Reserved).', max_length=255)),
                ('orders_or_directions', models.TextField(blank=True, default='', help_text='Judicial orders, directions, or procedural requirements issued by the court.')),
                ('next_hearing_date', models.DateField(blank=True, db_index=True, null=True)),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Confidential notes for lawyers/firm staff only. Never exposed to clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_records', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hearing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-hearing_date', '-created_at'],
                'indexes': [models.Index(fields=['case', '-hearing_date'], name='cases_heari_case_id_3efa8e_idx')],
            },
        ),
    ]
