# Generated by Django 6.0.7 on 2026-08-05 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(db_index=True, editable=False, help_text='Auto-generated reference, e.g. CONS-2026-0001.', max_length=32, unique=True)),
                ('practice_area', models.CharField(blank=True, choices=[('CIVIL', 'Civil Law'), ('CORPORATE', 'Corporate Law'), ('CRIMINAL', 'Criminal Law'), ('FAMILY', 'Family Law'), ('PROPERTY', 'Property Law'), ('TAX', 'Tax & Compliance')], max_length=32, null=True)),
                ('consultation_mode', models.CharField(choices=[('OFFICE', 'Office Visit'), ('PHONE', 'Phone Call'), ('VIDEO', 'Video Call')], max_length=16)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('issue_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='consultatio_client__78aef0_idx'), models.Index(fields=['status', '-created_at'], name='consultatio_status_49d4ed_idx')],
            },
        ),
    ]
