# Generated by Django 6.0.7 on 2026-08-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_practice_area_and_assignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consultation',
            new_name='consultatio_assigne_76855d_idx',
            old_name='consultatio_assigne_idx',
        ),
    ]
