# Generated by Django 6.0.7 on 2026-09-07 17:29

from django.conf import settings
from django.db import migrations, models


def mark_existing_consultations_paid(apps, schema_editor):
    Consultation = apps.get_model('consultations', 'Consultation')
    Consultation.objects.all().update(payment_status='PAID')


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_consultatio_assigne_idx_consultatio_assigne_76855d_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.RunPython(
            mark_existing_consultations_paid,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['payment_status', '-created_at'], name='consultatio_payment_660312_idx'),
        ),
    ]

