# Generated by Django 6.0.7 on 2026-09-07 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_appointment_fee'),
        ('consultations', '0004_consultation_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='case_appointment',
            field=models.ForeignKey(blank=True, help_text='Linked case for an existing-case appointment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_appointments', to='cases.case'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='charged_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Historical fee in INR charged at the time of booking.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(choices=[('NEW_MATTER', 'New Legal Matter'), ('EXISTING_CASE', 'Existing Case Appointment')], db_index=True, default='NEW_MATTER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['consultation_type', '-created_at'], name='consultatio_consult_606c54_idx'),
        ),
    ]
