# Generated by Django 6.0.7 on 2026-09-09 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_appointment_fee'),
        ('consultations', '0005_consultation_case_appointment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerAvailabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_duration', models.PositiveIntegerField(choices=[(30, '30 minutes'), (45, '45 minutes')], default=30, help_text='Standard duration of consultation appointments in minutes.')),
                ('is_available', models.BooleanField(default=True, help_text='Master toggle indicating whether the lawyer is accepting consultations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawyerDateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of override (inclusive).')),
                ('end_date', models.DateField(help_text='End date of override (inclusive).')),
                ('is_unavailable', models.BooleanField(default=True, help_text='True if completely unavailable all day. False if available with custom hours.')),
                ('start_time', models.TimeField(blank=True, help_text='Custom start time if available.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Custom end time if available.', null=True)),
                ('reason', models.CharField(blank=True, default='', help_text='Optional reason for override (e.g., Vacation, Leave, Special Session).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LawyerTimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of time block.')),
                ('start_time', models.TimeField(help_text='Start time of block.')),
                ('end_time', models.TimeField(help_text='End time of block.')),
                ('reason', models.CharField(choices=[('COURT', 'Court Appearance'), ('PERSONAL', 'Personal Commitment'), ('MEETING', 'Internal Meeting'), ('LEAVE', 'Leave / Travel'), ('OTHER', 'Other Professional Commitment')], default='COURT', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='LawyerWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday).')),
                ('start_time', models.TimeField(help_text='Start of consultation working period.')),
                ('end_time', models.TimeField(help_text='End of consultation working period.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Consultation duration in minutes (30 or 45).'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Calculated consultation end time.', null=True),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['preferred_date', 'preferred_time'], name='consultatio_preferr_b8ab61_idx'),
        ),
        migrations.AddField(
            model_name='lawyeravailabilityprofile',
            name='lawyer',
            field=models.OneToOneField(limit_choices_to={'role__in': ('SENIOR_LAWYER', 'JUNIOR_LAWYER')}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerdateoverride',
            name='lawyer',
            field=models.ForeignKey(limit_choices_to={'role__in': ('SENIOR_LAWYER', 'JUNIOR_LAWYER')}, on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyertimeblock',
            name='lawyer',
            field=models.ForeignKey(limit_choices_to={'role__in': ('SENIOR_LAWYER', 'JUNIOR_LAWYER')}, on_delete=django.db.models.deletion.CASCADE, related_name='time_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyerweeklyschedule',
            name='lawyer',
            field=models.ForeignKey(limit_choices_to={'role__in': ('SENIOR_LAWYER', 'JUNIOR_LAWYER')}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
