# Generated by Django 6.0.7 on 2026-07-28 18:24

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier.', max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(help_text='Display name used across the chambers portal.', max_length=255, verbose_name='full name')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Optional contact number (e.g. +91 …).', max_length=20, verbose_name='phone number')),
                ('role', models.CharField(choices=[('ADMIN', 'Firm Administrator'), ('SENIOR_LAWYER', 'Senior Advocate'), ('JUNIOR_LAWYER', 'Junior Advocate'), ('PARALEGAL', 'Paralegal'), ('CLIENT', 'Client')], db_index=True, default='CLIENT', help_text='Chambers access role.', max_length=32, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot authenticate.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can access the Django admin site.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
    ]
