# Generated by Django 6.0.7 on 2026-10-07 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0006_case_appointment_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='cases.case')),
            ],
            options={
                'verbose_name': 'Case Conversation',
                'verbose_name_plural': 'Case Conversations',
                'db_table': 'chat_case_conversations',
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.caseconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_case_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Message',
                'verbose_name_plural': 'Case Messages',
                'db_table': 'chat_case_messages',
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('content__regex', '^\\s*$'), _negated=True), name='chat_message_content_not_empty_or_whitespace')],
            },
        ),
    ]
