# Generated by Django 6.0.7 on 2026-10-08 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_appointment_fee'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseconversation',
            name='conversation_type',
            field=models.CharField(choices=[('CLIENT_LAWYER', 'Client Lawyer'), ('TEAM', 'Team')], db_index=True, default='CLIENT_LAWYER', max_length=20),
        ),
        migrations.AlterField(
            model_name='caseconversation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='cases.case'),
        ),
        migrations.AddConstraint(
            model_name='caseconversation',
            constraint=models.UniqueConstraint(fields=('case', 'conversation_type'), name='unique_case_conversation_type'),
        ),
    ]
