# Generated by Django 6.0.7 on 2026-10-08 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_caseconversation_conversation_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='casemessage',
            name='chat_message_content_not_empty_or_whitespace',
        ),
        migrations.AddField(
            model_name='casemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat/attachments/'),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='attachment_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='casemessage',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='casemessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content__regex', '^\\s*$'), _negated=True), models.Q(('attachment__isnull', False), models.Q(('attachment', ''), _negated=True)), _connector='OR'), name='chat_message_content_or_attachment_required'),
        ),
    ]
