# Generated by Django 6.0.7 on 2026-09-07 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0004_consultation_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Transaction amount in integer paise (e.g. 50000 = ₹500.00).')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, help_text='Order ID returned by Razorpay server-side Orders API.', max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, db_index=True, help_text='Payment ID returned by Razorpay after successful capture.', max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, default='', help_text='HMAC-SHA256 signature returned by Razorpay checkout.', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment verification succeeded and status became CAPTURED.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='consultations.consultation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consultation', '-created_at'], name='payments_pa_consult_bdbd8c_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'), models.Index(fields=['razorpay_order_id'], name='payments_pa_razorpa_86ad18_idx'), models.Index(fields=['razorpay_payment_id'], name='payments_pa_razorpa_4059b1_idx')],
            },
        ),
    ]
